### ISSUE TITLE
Discount calculator breaks with: Class 'Redshop\Promotion\RedshopHelperProductPrice' not found

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5215]
The discount calculator breaks and i get this error :

Class 'Redshop\Promotion\RedshopHelperProductPrice' not found

I think its because of a missing \ in:
libraries\redshop\src\Promotion\Discount.php:179
$productNetPrices = RedshopHelperProductPrice::getNetPrice($productId)
>>
$productNetPrices = \RedshopHelperProductPrice::getNetPrice($productId)

But when i changed that i get other errors. So please test it through.

**Comment by ducredweb** [comment]
Thank you @Rmh1978   for reporting it.
We will set up that discount calculator in the admin and send fix to this one as soon as possible.
@NguyenBao10   please take a look and fix.

**Comment by hoang-tran-redweb** [comment]
@Rmh1978 I fixed, please check again. Tkank you.

**Comment by Rmh1978** [comment]
@hoang-tran-redweb   where did you fix it?
There is no change on:
mydomain.dk/tmp/testsite215clean/

**Comment by hoang-tran-redweb** [comment]
@Rmh1978 I fixed on pull request. https://github.com/redCOMPONENT-COM/redSHOP/pull/5233

**Comment by Rmh1978** [comment]
@hoang-tran-redweb    Confirmed fixed.

Is there a way to download the fixed files?
I had to copy all changes to my sitesites one by one.

**Comment by anhredweb** [comment]
@Rmh1978 in case you has forked redSHOP to your local computer, please follow those step bellow to get latest code from redSHOP. Open terminal and go to redSHOP source directory, then:
`git remote add upstream git@github.com:redCOMPONENT-COM/redSHOP.git`
Now you check `git remote -v` you will has 02 remote:
- `origin` is your forked source
- `upstream` link to redCOMPONENT/redSHOP
After that, to ensure you are at `develop` branch please run:
`git checkout develop`
You need to fetch latest information from update by:
`git fetch upstream`
Then you merged latest change to your local computer by:
`git merge upstream/develop`
It's not done yet, you need put back all those updated code to forked repo on github by:
`git push origin develop`
Completed, and everytime you need to get latest code, please re-do these step. More knowledge to use git, please refer at: https://git-scm.com/doc

Regards.
