### ISSUE TITLE
Product attribute pre-select don´t work

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5219]
Product view with attributes. I have pre-selected the top attribute-value of each set. But in frontend no attribute is pre-selected.
It worked in RS 2.1.5

@NguyenBao10

**Comment by hungnguyenckc** [comment]
Hi @Rmh1978 i fixed this problem in PR https://github.com/redCOMPONENT-COM/redSHOP/pull/5205/files and it will be release in redshop 3.0.1

**Comment by Rmh1978** [comment]
Great :-)
