### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<'   from cart module

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5222]
I am getting a error:
Uncaught SyntaxError: Unexpected token '<'

It coming from the Cart module. 
The file 
modules\site\mod_redshop_cart\tmpl\default.php
is not in the RS 3.0 package so i also can´t override it. I am not familiar with the new twig you implementet.

@NguyenBao10

**Comment by NguyenBao10** [comment]
Yes, thank you Ronni, we see the issue, too. My colleague @hoang-tran-redweb  will fix and send the link pull request to you soon

**Comment by NguyenBao10** [comment]
We fixed here https://github.com/redCOMPONENT-COM/redSHOP/pull/5225 @Rmh1978

**Comment by Rmh1978** [comment]
Great.

Confirm fix.
