### ISSUE TITLE
File upload does not respect allowed file ext from RS config.

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5232]
Since about version RS 2.1 the Product file upload has not respectet the Allowed file extentions from RS configuration. I have reportet it, but now i made a fix for it.

It throws the error that the file ext is not allowed, but it still finish the upload of the file and show it in the list.

file : components/com_redshop/controllers/product.php:826 :
Old:
if (JFile::upload($uploadFileData['tmp_name'], $uploadFilePath)) {
New:
if (JFile::upload($uploadFileData['tmp_name'], $uploadFilePath) **&& in_array(strtolower($fileExtension), $legalExts**)) {

To not get double error message.
file : components/com_redshop/controllers/product.php:853 add new code :
elseif (!in_array(strtolower($fileExtension), $legalExts)) {
}

Fix is testet and works on live site.

@NguyenBao10

**Comment by NguyenBao10** [comment]
I have another way to fix this https://github.com/redCOMPONENT-COM/redSHOP/pull/5254/files , please follow up, then apply to your site after its merged

**Comment by Rmh1978** [comment]
Much better. Thanks.
Works.
