### ISSUE TITLE
Checkout Shipping modal popup errors

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5236]
In Checkout > Edit shipping address.

When the modal opens it throws errors.

- Uncaught SyntaxError: Invalid or unexpected token
- GET https://www.mydomain.dk/tmp/testsite215clean/ net::ERR_ABORTED 500
- Uncaught TypeError: $(...).select2 is not a function

When i click save it seems like it saves the changes, but it does not return to Checkout view.

Create new shipping address also throws error, but function works.

RS 3.0 / Joomla 3.9.15
@NguyenBao10

**Comment by NguyenBao10** [comment]
I send pr here https://github.com/redCOMPONENT-COM/redSHOP/pull/5256 , a minor mistake when refactor

**Comment by Rmh1978** [comment]
The fix works.

But i stil get a 
GET https://www.mydomain.dk/tmp/testsite215clean/ net::ERR_ABORTED 500  jquery-migrate.min.js:2

**Comment by anhredweb** [comment]
@Rmh1978 We're verifying your report. Will update feedback to you.

Regards,
redSHOP Team.

**Comment by NguyenBao10** [comment]
Hi @Rmh1978 , I try on both of redshop and your site, but I do not see errors you report, could you please give me more picture or video through email?

**Comment by Rmh1978** [comment]
Hi @NguyenBao10 
You are right. I think there was some cache hidden when i testet last time. 

All good.
