### ISSUE TITLE
Account page > Coupon list error

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5260]
On the Account page view. When the   is present on the account page it breaks and gets :
1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '14:04:40 AND `c`.`amount_left` > 0' at line 3

It seems like it the db code here :
components/com_redshop/models/account.php:104

**Comment by anhredweb** [comment]
@Rmh1978 We're verifying your report. Will update feedback to you.

Regards,
redSHOP Team.

**Comment by hungnguyenckc** [comment]
@Rmh1978 i fixed in PR refactor #5237 an it will be release in upcoming version

**Comment by Rmh1978** [comment]
Thank you @hungnguyenckc
