### ISSUE TITLE
Add to cart error with userfield "file upload" 

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5261]
When you try to Add a product to Cart that has a userfield uploaded file, then it breaks and show :
0 - Class 'Redshop\User\JText' not found

**Comment by anhredweb** [comment]
@Rmh1978 We're verifying your report. Will update feedback to you.

Regards,
redSHOP Team.

**Comment by Rmh1978** [comment]
HI @anhredweb and @hoang-tran-redweb 

Thank you for the fix in  #5277 
It fixed the error when adding to cart.

The error was that it failed with TEXT warning that this field is required. But i am uploading a file so it should not trigger that warning.
I guess there is someting wrong with the   userFieldValidation.

**Comment by NguyenBao10** [comment]
Yes, Hoang is fixing it, will let you know as soon as he is done

**Comment by ducredweb** [comment]
@hoang-tran-redweb    what is the status?

**Comment by hoang-tran-redweb** [comment]
@Rmh1978 please pull the latest code from "develop" branch of redshop repository, using Gulp to release the laster package zip installation file and install/update redshop on your site (fresh clean redshop with no core-hacked), and get back to us if the fix PR works as expected. Thanks!

**Comment by NguyenBao10** [comment]
do you try with the latest version @Rmh1978 ?

**Comment by Rmh1978** [comment]
I just installed the latest dev build and in this build the calculator form in not present. Only the calc button outputs. So can´t test.

![calc](https://user-images.githubusercontent.com/61828802/85115957-d6c0a800-b21c-11ea-9d83-79339644d6dd.jpg)

**Comment by Rmh1978** [comment]
I uploaded the file components/com_redshop/views/product/tmpl/default_calculator.php
from the official 3.0.1 so show the form.

The issue is resolved but now another one came.

When i have uploaded a file correct and click Add to cart, then it alerts "Print file required". So it does not recoqnize the uploaded file and the field is required.

Try it here : www.mydomain.dk/tmp/testsite3.x.clean/kanvas-larred

**Comment by NguyenBao10** [comment]
https://github.com/redCOMPONENT-COM/redSHOP/pull/5277
https://github.com/redCOMPONENT-COM/redSHOP/pull/5387

above errors will be fixed in those pr @Rmh1978

**Comment by Rmh1978** [comment]
Great. I will check in release 3.0.2

**Comment by Rmh1978** [comment]
Confirmed working in 3.0.2
