### ISSUE TITLE
Add to cart. No selected attribute error message

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5262]
When you try to Add to cart without choosing a required Attribute it triggers a page/browser popup.

This popup shows :

www.domain.dk says:
Please select 
Attribute name`<br>`Attribute name`<br>`Attribute name`<br>`Attribute name`<br>`Attribute name`<br>`Attribute name

In this case my Attribute has 6 subproperties so the Popup message ads 6 x the Attribute name with `<br>` tag.
It should only show 1x like this

www.domain.dk says:
Please select 
Attribute name

**Comment by anhredweb** [comment]
@Rmh1978 We're verifying your report. Will update feedback to you.

Regards,
redSHOP Team.

**Comment by NguyenBao10** [comment]
We fix here https://github.com/redCOMPONENT-COM/redSHOP/pull/5276/files @Rmh1978

**Comment by Rmh1978** [comment]
I tried to apply the fix but it still makes a badly-styled error popup.

The lines in the fix did not match, so maybe you have made another change in libraries/redshop/src/Attribute/Helper.php

First line change should be on 245 but in my package it was on 243.

**Comment by ducredweb** [comment]
@Rmh1978   please pull the latest code from "develop" branch of redshop repository, using Gulp to release the laster package zip installation file and install/update redshop on your site (fresh clean redshop with no core-hacked), and get back to us if the fix PR works as expected. Thanks!

**Comment by Rmh1978** [comment]
Hi @ducredweb 
I am pretty new to github.

Is there a easy way to download the zip install package?
Without forking etc.

I tried to download the the zip with "Clone or download" and then override the coresponding files in my folders on my server.

It seems like some issues have been fixed but this issue is still there, but not sure if this "update" method works.

**Comment by NguyenBao10** [comment]
Hi @Rmh1978 , which version do you try, 3.0.1 or previous?

**Comment by Rmh1978** [comment]
I just tried with the latest dev 3.0.2 and its still the same issue.

![attr](https://user-images.githubusercontent.com/61828802/85115278-b6441e00-b21b-11ea-84b0-4e59097c124c.jpg)

It says "Please select" and then 3x Atrribute name (Skæring?) with <br> in between. I guess the browser alert does not allow tags.

So it should only say 
"Please select Atrribute name"

I think now it count the Atrribute value and then output Atrribute name that count (3x).

**Comment by NguyenBao10** [comment]
https://github.com/redCOMPONENT-COM/redSHOP/pull/5388 we will fix it in this pr @Rmh1978

**Comment by Rmh1978** [comment]
Confirmed working. Thank you.
