### ISSUE TITLE
[REDSHOP-5936] Admin > Coupon > Add new > User specific = slow loading list

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5266]
When you add a new coupon that are user specific, load the user list and have a long user list it takes a long time to load the list.
Please limit the list. There is a search field so there is no reason to load all users.

**Comment by anhredweb** [comment]
@Rmh1978 We're verifying your report. Will update feedback to you.

Regards,
redSHOP Team.

**Comment by NguyenBao10** [comment]
Hi @Rmh1978 we have another solution for it, but it will take time to do, I will let you know as soon as its done

**Comment by Rmh1978** [comment]
I also noticed that if i do a search, it will also show the ST users when i search with email. I hope your solution will also fix that.

**Comment by hoang-tran-redweb** [comment]
@Rmh1978 I fixed on PR https://github.com/redCOMPONENT-COM/redSHOP/pull/5363. Please pull and check again.

**Comment by anhredweb** [comment]
@Rmh1978 Issue fixed and merged to latest code.

**Comment by Rmh1978** [comment]
Thank you :-)
