### ISSUE TITLE
[REDSHOP-5949] Admin > Order detail view > Update discount error

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5279]
If you update the discount on a order and update again with the same amount it triggers COM_REDSHOP_ERROR_UPDATING_DISCOUNT

I don´t know if thats meant to be, but its still stange it triggers a message like this.
The text is a error text, but the message type is "message" and not "error". So you don´t really notice the error because the system-message-container is green and not red.

**Comment by hoang-tran-redweb** [comment]
@Rmh1978 I fixed in PR. https://github.com/redCOMPONENT-COM/redSHOP/pull/5361

**Comment by Rmh1978** [comment]
I checked with a dev package from 19/6 and the seach field is really fast not. Perfect.

But it seems like it does not find all users.
