### ISSUE TITLE
Admin > Order view. Top menu with search, date, payment and status is a visuel mess

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5287]
Please incorperate these css changes in /media/com_redshop/css/redshop.admin.css

.select2-container{display: inherit !important}
#filter,#filter_from_date,#filter_to_date,#keyword{height: 40px !important}
#search{color: #fff;background-color:#7f7f7f;height:40px}

It will style the filterTool area nicely.

**Comment by anhredweb** [comment]
Hi @Rmh1978,

We've just checked view order at backend and there's no issue with it. Can you help us by send some screenshots or captured screen videos.

Regards,
redSHOP team.

**Comment by Rmh1978** [comment]
I have sent a screenshot to @NguyenBao10  on email.

**Comment by NguyenBao10** [comment]
we will fix it in REDSHOP-5962

**Comment by Rmh1978** [comment]
Hi @NguyenBao10 
I cannot find a REDSHOP-5962 but thank you.
