### ISSUE TITLE
Postdanmark plugin > Checkout shipping address on order reciept email

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5300]
When using the Postdanmark plugin (optional pickup point) as shipping and selecting a pickup Shop id in Checkout and finalize the order.
The shipping address on the order reciept on the site the the Pickup point address correctly. But the order reciept email shows the Billing address as Shipping address and not the Pickup point address.

It saves the the shop id correctly in the db for the order. So it seems like the order email is triggered before the db is updated, so it can pull the pickup point/ shop id info.

So please delay the order email so the shipping address is correct in the order email.

And please update Postdanmark to PostNord as it is called now.

RS 3.0.1

**Comment by anhredweb** [comment]
Hi @Rmh1978 , 
We're going to verify your report soon.
Thanks for your sharing.
redSHOP team.

**Comment by hungnguyenckc** [comment]
Hi @Rmh1978 
we're fixed in PR #5345 but please go to website redcomponent.com download 2 packet 
**Post Danmark** and **PostDanmark Product Plugin** lastest

**Comment by Rmh1978** [comment]
Hi @hungnguyenckc 

Perfect. Works.

Thank you.
