### ISSUE TITLE
Checkout validation termscondition dont work with excisting user

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5301]
If a excisting user that already has accepted termscondition try to checkout nothing happens. Checkout returns false and the alert is not triggered.

If i remove !document.getElementById('termscondition').checked from this validation  in /media/js/redshop.common.js  it works. So there is something wrong with the user check. 

`	if (!document.getElementById('termscondition').checked && flagOneStep != 1) {
		alert(Joomla.JText._('COM_REDSHOP_PLEASE_SELECT_TEMS_CONDITIONS'));
		return false;
	}`

RS 3.0.1

**Comment by anhredweb** [comment]
Hi @Rmh1978 , 
We're going to verify your report soon.
Thanks for your sharing.
redSHOP team.

**Comment by Rmh1978** [comment]
Try it here : www.mydomain.dk/tmp/testsite215clean/checkout

I do it with my test user that has db > redshop_users_info > accept_terms_conditions = 1
So the checkbox with accept terms do not show up in Final checkout. Then the error occours.

**Comment by VanTrieuThanh** [comment]
Hi @NguyenBao10 help me reproduce this issue

**Comment by ducredweb** [comment]
This seems to be a cross-browser incompatibility, what is your browser @Rmh1978 ?

**Comment by Rmh1978** [comment]
Normally i use Chrome. But also tested with Firefox IE with same issue.

**Comment by Rmh1978** [comment]
This code in redshop.common.js :
`if (!document.getElementById('termscondition').checked && flagOneStep != 1) {`

Is this part 
`!document.getElementById('termscondition').checked`
also checking in db >> _redshop_users_info >> accept_terms_conditions = 1
when a user already has checked the termscondition with a previous order?

This validation is new in RS 3.

**Comment by hoang-tran-redweb** [comment]
@Rmh1978 I fixed on PR https://github.com/redCOMPONENT-COM/redSHOP/pull/5372. Please pull code and check again.

**Comment by NguyenBao10** [comment]
Please try again with Hoang's pr @Rmh1978

**Comment by Rmh1978** [comment]
I have downloaded a clone and it seems to be fixed. Hope my "clone" is downloaded correct.
