### ISSUE TITLE
Postdanmark plugin optional pickup point - http/ https

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5303]
It seems like the plugin is made for a http only site. I am running a https site (like most webshops).
It throw this warning:
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure image '<URL>'. This content should also be served over HTTPS.

Please update the plugin so it serves data correct with https sites.

**Comment by anhredweb** [comment]
Hi @Rmh1978 , 
We're going to verify your report soon.
Thanks for your sharing.
redSHOP team.

**Comment by NguyenBao10** [comment]
Hi @Rmh1978 , i try on yourdomain/tmp/testsite215clean/index.php?option=com_redshop&view=checkout&Itemid=176&lang=da , but do not see the problem.

**Comment by Rmh1978** [comment]
Hi @NguyenBao10 

You are right.

I think i where running a "old" version of the plugin and updated it from redcomponent some weeks ago.
I was runing same version number that was on redcomponent, but there was changes in the version on redcomponent.
