### ISSUE TITLE
Postdanmark plugin optional pickup point - "Choose pickup point" button

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5304]
When the plugin is the top of the list of shipping methods in Checkout the "Choose pickup point" button does not show. So you need to first select another shipping method and back to the Postdanmark plugin to trigger the Button.

RS 3.0.1

**Comment by anhredweb** [comment]
Hi @Rmh1978 , 
We're going to verify your report soon.
Thanks for your sharing.
redSHOP team.

**Comment by hungnguyenckc** [comment]
Hi @Rmh1978 
We're fixed the problem and update on redcomponent.com you can go to site and download

**Comment by Rmh1978** [comment]
Confirmed and works. Thank you.
