### ISSUE TITLE
Postdanmark plugin optional pickup point - Popup map zip code

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5305]
With Onestep checkout and not logged in/ creating a user. When I have filled the user billing fields and then go to select a pickup point the map is not loading. So it is not fetching the ZIP from the billing field in the registration form.
I can seach the ZIP manually but this load view looks like it is broken and will confuse customers.

RS 3.0.1

**Comment by anhredweb** [comment]
Hi @Rmh1978 , 
We're going to verify your report soon.
Thanks for your sharing.
redSHOP team.

**Comment by Rmh1978** [comment]
When PR #5345 was fixed or i updated the plugin this also works.
I was runing the same version of the plugin as there was on Redcomponent, but there where still code updates in js and default.php files.

Works for me now.
