### ISSUE TITLE
Replace Shipping Address block {shipping_address_start}...{shipping_address_end} - {companyname}

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5306]
When a private user creates a order then the shipping address on the order reciept show the tag 
 {companyname}

I changed the code in /libraries/redshop/src/Shipping/tag.php  that works like below.
It should be “if (!empty($shippingAddress->company_name))”
because with Postdanmark plugin pickup point it show the shop_id and Post Danmark, as Company name that the customer should not see.

RS 3.0.1 code:
if ($shippingAddress->is_company == 1) {
self::replaceTag(
$shippingData,
$shippingAddress->company_name,
array('{companyname}', '{companyname_lbl}'),
array($shippingAddress->company_name, \JText::_('COM_REDSHOP_COMPANY_NAME'))
);
}

Updated code:
			if (!empty($shippingAddress->company_name)) {
				self::replaceTag(
					$shippingData,
					$shippingAddress->company_name,
					array('{companyname}', '{companyname_lbl}'),
					array($shippingAddress->company_name, \JText::_('COM_REDSHOP_COMPANY_NAME'))
				);
			}
			else {
				self::replaceTag(
					$shippingData,
					$shippingAddress->company_name,
					array('{companyname}', '{companyname_lbl}'),
					array("", "")
				);
			}

When you work on this block anyway, could you then add a check to the IF block so when the customer chooses self_pick then the shipping address on the order detail/ receipt etc should be emty.
Some customers gets confused because the Billing address is Shipping address when they have selected Self pickup at the Webshops location.

RS 3.0.1

**Comment by anhredweb** [comment]
Hi @Rmh1978 , 
We're going to verify your report soon.
Thanks for your sharing.
redSHOP team.

**Comment by VanTrieuThanh** [comment]
Hi @Rmh1978 
I don't reproduce your bug. I don't see tag {company_name} in Order receipt 
![Screenshot from 2020-04-16 16-48-05](https://user-images.githubusercontent.com/44457418/79442232-776acf80-8002-11ea-91d1-19c5acfdca7d.png)

Or you mention the name on First name in Shipping Address?
![Screenshot from 2020-04-16 16-20-07](https://user-images.githubusercontent.com/44457418/79442115-530ef300-8002-11ea-8573-b427a14c14bd.png)

**Comment by Rmh1978** [comment]
Thats strange.

My code in the order_reciept template looks like :
`{shipping_address_start}`
`<div>{companyname}</div>`
`<span style="font-size: 9pt;">`
`{firstname} {lastname}<br />`
`{address}<br />`
`{zip} {city}<br />`
`</span>`
`{shipping_extrafield}{shipping_address_end}`


**Shipping info with Private user:**

![ship company](https://user-images.githubusercontent.com/61828802/79445170-7cb52380-7fdc-11ea-85f7-dc3875ab7ae1.jpg)

**Shipping info with a Company user:** 

![ship company 1](https://user-images.githubusercontent.com/61828802/79445537-1d0b4800-7fdd-11ea-8679-cbfcbc450334.jpg)

**Comment by VanTrieuThanh** [comment]
Hi @NguyenBao10 help me reproduce this issue

**Comment by NguyenBao10** [comment]
Hi @Rmh1978 , it should be {company_name} instead of {companyname}

**Comment by Rmh1978** [comment]
Hi @NguyenBao10 

I dont think so. In the template tag list it also says {companyname}

In my example it also works with is_company=1 so it displays the company name in {companyname}
I tried to change to {company_name} on the Order_reciept template and then the tag dont parse at all.

**Comment by NguyenBao10** [comment]
we fix here https://github.com/redCOMPONENT-COM/redSHOP/pull/5453 @Rmh1978

**Comment by Rmh1978** [comment]
Works. Thank you.
