### ISSUE TITLE
Admin > Product detail view > SEO > Canonical Url

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5307]
There is a red box saying ” You must enable/install <i>canonical</i> product plugin to use this feature.”
The plugin is installed and enabled on my site. So could you make a IF plugin enabled on this warning.

Mostly to not confuse new users to Redshop, but also to just do it correct.

RS 3.0.1

**Comment by anhredweb** [comment]
Hi @Rmh1978 , 
We're going to verify your report soon.
Thanks for your sharing.
redSHOP team.

**Comment by anhredweb** [comment]
Hi @Rmh1978 ,
Could you pleae send me zip of the Canonical plugin you installed on your site **via my email** anh@redweb.dk. This will help to to identify the bug

Thanks,
redSHOP team

**Comment by anhredweb** [comment]
@Rmh1978 : you can follow status of the PR: PR: https://github.com/redCOMPONENT-COM/redSHOP/pull/5313

Thanks,
redSHOP Team.
