### ISSUE TITLE
Discount calculator dont output price in {product_price_novat} with Product default price = 0

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5309]
I have some products that has a default Product price = 0 and only get the final Product price that are added to cart from Discount calculator prices and attribute prices.

But when the Product default price is 0,- then the tag {product_price_novat} dont output a price when you use the Discount calculator.

I have commentet the if function here so it works :
libraries\redshop\helper\product\price.php:572

`// if ($productPrices['product_price_novat'] != "")`
`// {`
`$displayPriceNoVAT = '<span id="display_product_price_no_vat' . $productId . '">' . $priceNoVAT . '</span>';`
`// }` 

I can´t really see why the IF is there in the first place.

RS 3.0.1

**Comment by anhredweb** [comment]
Hi @Rmh1978 , 
We're going to verify your report soon.
Thanks for your sharing.
redSHOP team.

**Comment by Rmh1978** [comment]
This work with fix in #6023 

Thanks.
