### ISSUE TITLE
Checkout Shipping selection wrong

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5314]
In Checkout I have a extra Shipping address (ST user) on my Test account. When i select "Same as Billing" for shipping, then it is still the ST user that is booked as Shipping on the order.

**Selection in Checkout (BT user "Test konto company"):**
![SHipping same as](https://user-images.githubusercontent.com/61828802/79570043-076b5080-80b9-11ea-836a-48dbaa24bcb4.jpg)

**Shipping address on order reciept (ST user):**
![Shipping wrong](https://user-images.githubusercontent.com/61828802/79570054-0b976e00-80b9-11ea-87ad-a65e7a3e94ba.jpg)

.
.
A small extra issue regarding this. When there is a ST user present then it pre selects the ST user and not the BT user.
In my experience with customers in real life this it not smart for customers as they wan´t shipping to the BT address most of the times and sometimes uses the ST.
I have made a tweak so it always pre-select the BT user. It would be nice if you adapted that.

**Pre select when page load:** 
![Shipping preselected](https://user-images.githubusercontent.com/61828802/79570299-79dc3080-80b9-11ea-8c18-a7a561a3798e.jpg)

RS 3.0.1

**Comment by ducredweb** [comment]
I think something was wrong with your `onestepcheckout.php` or some billing/shipping templates in your template override folder, when switching multiple radios button of ST users, the system always re-validating the state and return response immediately to update prices, shipping rates, payments,...  to the DOM (without reload).
if you select "Same as Billing" for shipping, on order receipt page/ order mail it should always show correct shipping address based on choice.

**Comment by Rmh1978** [comment]
Hi @ducredweb 
I don´t have any template overrides for com_redshop, or core hacks on the site i am testing on.

**Comment by anhredweb** [comment]
@Rmh1978 Let me summarize your idea:
When there is your defined ST address, then pre-selected the ST address instead of `same as BT`. If that is I think this is good idea.

Thanks.

**Comment by Rmh1978** [comment]
Hi @anhredweb 

I just tested the original issue with a new dev build and that issue is solved.

About the extra issue you reffer to.
The way you describe is the way it works now. RS pre-selects a ST user if one is present. And i am saying in Live use this is not the best practice. At least for my customers. As they most of the times they ship to their BT address and then sometimes ship to a ST address.

But if it is proofed that pre-select ST-user if present is the best practice for the majority of RS users then just close the ticket, as i already have a Hack that pre-selects BT always.

**Comment by NguyenBao10** [comment]
Thank you for your idea but we will keep pre-selected the ST address @Rmh1978
