### ISSUE TITLE
Product review sorting, newest first

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5321]
Please sort the reviews from {form_rating} on the Product template with newest reviews first/ top.

It makes better sense to show the current option of the webshops customers, and not reviews that are maybe 3-4-5 years old.

RS 3.0.1

**Comment by hoang-tran-redweb** [comment]
@Rmh1978 I fixed in PR. https://github.com/redCOMPONENT-COM/redSHOP/pull/5359

**Comment by Rmh1978** [comment]
Nice. Thank you.
