### ISSUE TITLE
Custom fields description not saving or echo in admin Custom fields view

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5330]
It does not save the Description for custom user fields. I added it manually in db and it does not echo the Description in admin > Custom fields view.

Now i could display the Tooltip in frontend with the Description, but the Tooltip does not trigger either.
When you work on the Tooltip it could be a nice design feature to change the tooltip.png (all across Redshop) with Fontawesome fa-info-circle. Now that you include FA anyway.
The tooltip.png looks really outdated.
I did it on my site.

RS 3.0.1

**Comment by ducredweb** [comment]
Hi @Rmh1978  Ronni,
Your issue report is not very clear. Could you please provide us:
- Which field type and section are affected by this issue? or it always does not display the description value in all type and section of a custom field?
- About the tooltip, an end-user has the freedom to customize or use whatever image so that's up to you. Redshop does not care too much or force user for css, images, frontend layout, styling, etc... so it give you all the freedom of styling and design your frontpage
anyway, @hoang-tran-redweb  please verify the "Description" field issue and sending PR to fix if any

**Comment by Rmh1978** [comment]
Well i think it is all sections. I tried on these ones.

![userfield](https://user-images.githubusercontent.com/61828802/81483857-71eb5880-9241-11ea-9f21-ac6c4801c1a4.jpg)

**Comment by hoang-tran-redweb** [comment]
@Rmh1978 
I will issue not save the "description" field of the custom field core redshop.

**Comment by hoang-tran-redweb** [comment]
@Rmh1978 I fixed on core redshop, please apply pull request this.

https://github.com/redCOMPONENT-COM/redSHOP/pull/5339

File: 
+ component/admin/sql/updates/mysql/3.0.2.sql
+ component/site/layouts/fields/html.php
+ redshop.xml

**Comment by Rmh1978** [comment]
Hi @hoang-tran-redweb 

The changes works for saving description in Backend.

Now please fix:
libraries/redshop/src/Fields/SiteHelper.php:566
if (trim($data->**description**) != '' && $fieldType != 'hidden') {

That fixes the tooltip.png to echo.
Now it shows but it the Tooltip function don´t work.

This is my newest testsite with most Github code for 3.0.2
https://www.mydomain.dk/tmp/testsite3.x.clean/klistermarker/provetryk-klistermarke

**Comment by hoang-tran-redweb** [comment]
@Rmh1978 please fix help me. 
![image](https://user-images.githubusercontent.com/45586177/81790381-82484f80-952f-11ea-84ca-1b6bef81ee1d.png)

**Comment by Rmh1978** [comment]
Sorry. Should have explained.

You know my real domain. I won´t publish my real (test site) domain here for Google or others.

So change mydomain >> my real domain

**Comment by hoang-tran-redweb** [comment]
https://www.print.dk/tmp/testsite3.x.clean/klistermaerker

I don't see issue.

**Comment by hoang-tran-redweb** [comment]
@Rmh1978 I fixed on core redshop, please apply pull request this.

#5339

File: libraries/redshop/src/Fields/SiteHelper.php

**Comment by Rmh1978** [comment]
Thats not the link i posted.
See it here :
/klistermarker/provetryk-klistermarke
![tooltip old](https://user-images.githubusercontent.com/61828802/81792857-ea376f80-9508-11ea-8327-930d602fb99d.jpg)


And please REMOVE my domain from you link post. I don´t wan´t it indexed by Google.

**Comment by hoang-tran-redweb** [comment]
@Rmh1978 I see, but i don't see issue.

**Comment by Rmh1978** [comment]
Ok. It outputs. I just thought you had some styling on the Tooltip so it look like the backend Tooltip.

Now i can see when the it takes the title of the Tooltip as $data->name,  
it for me is not fitting. In my opinion it should be  $data->title,
Because $data->name,  is the name of the tag you use as userfield in templates. So you can´t just update the Title of the tooltip if you need to without breaking the userfield tag.

**Please remove my real url from your link on the post 1 hours ago.**
