### ISSUE TITLE
Reviews - show all reviews button

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5349]
If you set in RS config > Feature setting > Number of favoured reviews = 2 
and have eg. 10 reviews. Then you get the
`<a href="javascript:showallreviews();">`

But when you Show all reviews then the Show all reviews text is still visible and mixed in between the review.
Please make .show_reviews {display:none}   when showallreviews is triggered.

On my live site I have removed the reviewarrow.gif because i dont believe it look good. Maybe that could be done in the core. Then the users can style this much better with css or in language overrides.

![show all reviews](https://user-images.githubusercontent.com/61828802/82751795-0d400a00-9dba-11ea-8d15-c545dd02b0cd.jpg)

RS 3.0.1

**Comment by VanTrieuThanh** [comment]
Hi @Rmh1978  ,
We verified your report and create task for developer. We will inform you when it done
Thanks for your sharing.
redSHOP team.

**Comment by hoang-tran-redweb** [comment]
@Rmh1978 I fixed in PR. https://github.com/redCOMPONENT-COM/redSHOP/pull/5358

**Comment by Rmh1978** [comment]
Perfect. Works.
