### ISSUE TITLE
Product attribute > Attribute value price save error

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5438]
RS 3.0.2

When i go to Product > Product Atrribute > Attribute value > Add price :

1) If i try to add a new price "Add" button. Nothing happens. Js error.

2) If i edit a excisting price and click save i get this error:
Table 'mydomain_dk_db_testsite_302.product_attribute_price' doesn't exist

**Comment by VanTrieuThanh** [comment]
Hi @Rmh1978 ,
We're going to fix your report soon.
Thanks for your sharing.
redSHOP team.

**Comment by NguyenBao10** [comment]
Hi @Rmh1978 , I try with product "baotest" on your site, but i do not see the problem

**Comment by NguyenBao10** [comment]
we fixed here https://github.com/redCOMPONENT-COM/redSHOP/pull/5450 @Rmh1978

**Comment by Rmh1978** [comment]
Hi @NguyenBao10 

Seems to work. Thank you.
