### ISSUE TITLE
Cart view - Update quantity, update button

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5442]
RS 3.0.2

You made a new feature to Ajax update the Cart when the Quanity is changed.
REALLY nice feature :-)

Now the Update button is not needed anymore. So please remove it.

**Comment by VanTrieuThanh** [comment]
Hi @Rmh1978 ,
We're going to fix your report soon.
Thanks for your sharing.
redSHOP team.

**Comment by NguyenBao10** [comment]
https://github.com/redCOMPONENT-COM/redSHOP/pull/5448 we removed it here
