### ISSUE TITLE
Cart module - Delete product - No update

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5443]
RS 3.0.2

In the cart module, when you delete a product, then the Cart does not refresh to show the new status. 
So you need to refresh the page to get eg. Empty cart if you deleted the only product in cart.

**Comment by VanTrieuThanh** [comment]
Hi @Rmh1978 ,
We're going to fix your report soon.
Thanks for your sharing.
redSHOP team.

**Comment by NguyenBao10** [comment]
https://github.com/redCOMPONENT-COM/redSHOP/pull/5447 we fix it here @Rmh1978

**Comment by Rmh1978** [comment]
Hi @NguyenBao10 

Works. Thank you.
