### ISSUE TITLE
Discount calculation double price when 2x click - 3.0.2

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5462]
When you click the Calculate button the discount calculator calculates the price correct.

But if you click the calculate button one more time it doubles the price.
For my site it is wrong. I don´t know if there is a meaning by this behavior or it is a bug.

It has been there for a long time and i fixed it by commenting out this line:
`document.getElementById('main_price' + proid).value = product_price_excl_vat;`
in:
/media/com_redshop/js/redshop.attribute.js:1675

**Comment by NguyenBao10** [comment]
We fixed here https://github.com/redCOMPONENT-COM/redSHOP/pull/5472 @Rmh1978
