### ISSUE TITLE
Double code line in /libraries/redshop/src/Promotion/Discount.php

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5463]
I noticed it seems like there is 2 x 
`$calcOutput .= \JText::_('COM_REDSHOP_DISCOUNT_CALC_UNIT') . " " . $data['calcUnit'];`

On line 146 and 147 here:
 /libraries/redshop/src/Promotion/Discount.php

I don´t think thats correct.

RS 3.0.2

**Comment by NguyenBao10** [comment]
we fixed here https://github.com/redCOMPONENT-COM/redSHOP/pull/5472 @Rmh1978
