### ISSUE TITLE
Discount in % added in Admin add order does not show on Order reciept 

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5507]
When you create a Order in admin and add special Discount in % it does not show on the Order reciept or detail as discount.

Does it require another tag than {order_discount} ?

{special_discount} and {special_discount_amount} does not replace RS 3.0.2

**Comment by VanTrieuThanh** [comment]
Hi @Rmh1978 ,
We're going to verify your report soon.
Thanks for your sharing.
redSHOP team.

**Comment by NguyenBao10** [comment]
it requires {if special_discount} …{special_discount end if} , i sent pr to add them to list available tags here https://github.com/redCOMPONENT-COM/redSHOP/pull/5544 @Rmh1978
