### ISSUE TITLE
Admin > Order detail > Shipping label pdf > Phone = Zip

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5515]
I tried to make a template for the label that are createt here:
Admin > Order detail > Shipping label pdf

I edited the Template > Shipping label
But the tag {shipping_phone} is not outputting ST_phone but the Zip code.

RS 3.0.2

**Comment by VanTrieuThanh** [comment]
Hi @Rmh1978  ,
We're going to verify your report soon.
Thanks for your sharing.
redSHOP team.

**Comment by NguyenBao10** [comment]
hi @Rmh1978 , 
do you try with default template "shipping_pdf"? I try with it and see it's fine.
and if you create a new template, please make sure you choose "template section" is Shipping PDF.

**Comment by Rmh1978** [comment]
Hi @NguyenBao10 

Sorry. I did not see the reply.

If you look in:
component\admin\views\order_detail\view_pdf.php
about line 89

`$pdfTemplate = str_replace("{shipping_phone}", $shipping->zipcode, $pdfTemplate);`

This dosent look right :-)

**Comment by ducredweb** [comment]
ahh you're right @Rmh1978 , I reopened this issue and gonna apply a quick minor fix to this one (it has to be `$shipping->phone` for that replacement statement)

**Comment by Rmh1978** [comment]
Great. I fixed it on my live site. Nice it will be correct on next release.

**Comment by ducredweb** [comment]
https://github.com/redCOMPONENT-COM/redSHOP/pull/5554
