### ISSUE TITLE
[Feature request] posibility to sort categories by name

### ISSUE THREAD

**Issue by rbuelund** [redCOMPONENT-COM/redSHOP#5559]
Would be nice to have the ability to select sort order for categories by their title.

**Comment by NguyenBao10** [comment]
Hi @rbuelund , thanks for your request, your mean is sorting on category page in administrator or site

**Comment by rbuelund** [comment]
In frontend. As I see it in the global configuration for categories you do not have the posibility to set the sorting order to "Alphabetically a-z" or "Alphabetically z-a"

**Comment by rbuelund** [comment]
Is that something you would consider implementing?

**Comment by NguyenBao10** [comment]
hi @rbuelund , in redSHOP Configuration -> Categories , you can see option "Default Category Sorting" here, and if you chose "Category", it will sort by category name a-z now.

**Comment by rbuelund** [comment]
Are you gonna create a release with this change or how do I update ??

**Comment by NguyenBao10** [comment]
no, it had in the current version, did you see it?

**Comment by rbuelund** [comment]
Ahh yes - thank you.
