### ISSUE TITLE
Add to cart with attribute does not work!

### ISSUE THREAD

**Issue by rbuelund** [redCOMPONENT-COM/redSHOP#5560]
I have several products that do not work with attributes. The attributes are set as required - but even though you select an attribute in frontend, you still get the java message "Select the disc: is required" ?? I use redShop 3.0.2

I see this javascript error in the browser console: Error: Promised response from onMessage listener went out of scope

**Comment by rbuelund** [comment]
Any help on this??

**Comment by NguyenBao10** [comment]
Hi @rbuelund , it works fine with me, do you use Joomla's default templates or another?

**Comment by rbuelund** [comment]
I managed to fix this myself. The problem arises because of an old attribute.js file is still in the media/com_redshop/js folder after an update. I belive this file is now called redshop.attribute.js. After deletion of this old file, the attribute cart function works again. You should implement a clean of this js folder upon update. There are several files in there after an update wich are not in the 3.0.2 version!

**Comment by NguyenBao10** [comment]
Yes, we will recheck, thank you for your suggestion. If it works for you now, I will close this issue.
