### ISSUE TITLE
Vat not shown in cart

### ISSUE THREAD

**Issue by rbuelund** [redCOMPONENT-COM/redSHOP#5561]
I have this code in the cart template:

<tr>
<td>{vat_lbl}</td>
<td style="width: 100px;">{tax}</td>
</tr>

But the Vat is not shown - how come ?

**Comment by Rmh1978** [comment]
You need to wrap with :

`{if vat}
 {vat_lbl} : {tax}
 {vat end if}`

**Comment by rbuelund** [comment]
I have that - the VAT is still not shown. Has this something with shopping groups to do or why is it not showing ?

**Comment by NguyenBao10** [comment]
hi @rbuelund do you choose shopper group for tax rate?

**Comment by rbuelund** [comment]
Hmm.. how and where should I do that ?

**Comment by NguyenBao10** [comment]
it's in tax rate detail page, after clicking on "Products", you will see "VAT/Tax rates" item, it will show all tax rates you have after click on it, the last step is clicking on the tax rate you're using and choose "Shopper Group" for it.

**Comment by rbuelund** [comment]
Ahh yes - thank you - got it :-)
