### ISSUE TITLE
Pacsoft closing 15/6 - Fix for other users

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5594]
Hi

I use Pacsoft from Postnord. Pacsoft closes on 15/6-22 and we have to find another supplier.
nShift runs Pacsoft and the fix is easy if you choose nShift.

In file 
libraries/redshop/helper/order.php
Change this line:
$postURL = "https://www.pacsoftonline.com/ufoweb/order?session=po_DK"
to:
$postURL = "https://www.unifaunonline.com/ufoweb/order?session=ufo_DK"

**Comment by NguyenBao10** [comment]
Hi @Rmh1978 , thank you
