### ISSUE TITLE
Missing source of Utility in file?

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5624]
It looks like there is missing a source in:
/libraries/redshop/src/Promotion/Discount/Calculation.php

`$unit = Utility::getUnitConversation`
should be?
`$unit = \Redshop\Helper\Utility::getUnitConversation`

`$productUnit = Utility::getUnitConversation`
should be?
`$productUnit = \Redshop\Helper\Utility::getUnitConversation`

@NguyenBao10

**Comment by NguyenBao10** [comment]
https://github.com/redCOMPONENT-COM/redSHOP/blob/develop/libraries/redshop/src/Promotion/Discount/Calculation.php#L15

It had this line, so no need @Rmh1978 , did you get the errors with those code?

**Comment by Rmh1978** [comment]
Arhh, didnt notice that. It just looked strange when i saw it :-)

Closing issue @NguyenBao10
